/**
 * User-facing strings for the calendar page.
 * Extracted for i18n readiness — replace this file with a locale loader when adding translations.
 */
export const strings = {
  // Header
  headerEyebrow: 'MOE SCHEDULE',
  headerTitle: 'Calendar',
  headerLoading: 'Loading\u2026',

  // Header buttons
  quickAdd: 'Quick add',
  recurring: 'Recurring',
  calendarPdf: 'Calendar PDF',
  schedulePdf: 'Schedule PDF',
  conflicts: 'Conflicts',

  // Filter bar
  searchPlaceholder: 'Search school, class or teacher',
  searchLabel: 'Search lessons',
  filterTeacherLabel: 'Filter by teacher',
  filterSchoolLabel: 'Filter by school',
  allTeachers: 'All teachers',
  unassigned: 'Unassigned',
  cancelledClasses: 'Cancelled classes',
  allSchools: 'All schools',
  clearFilters: 'Clear',
  clearFiltersLabel: 'Clear all filters',
  lessonsCount: (n: number) => `${n} lessons`,

  // Bulk toolbar
  bulkLabel: 'Bulk operations',
  selectVisible: 'Select visible lessons',
  selected: (n: number) => `${n} selected`,
  moveDateLabel: 'Move selected lessons to date',
  move: 'Move',
  assignTeacherLabel: 'Assign selected lessons to teacher',
  assignTeacher: 'Assign teacher...',
  assign: 'Assign',
  cancelClasses: 'Cancel classes',
  delete: 'Delete',

  // Workload panels
  teacherWorkloadLabel: 'Teacher workload summary',
  schoolWorkloadLabel: 'School workload summary',
  visibleRange: 'VISIBLE RANGE',
  teacherWorkload: 'Teacher workload',
  lessonsBySchool: 'Lessons by school',
  cancelled: 'Cancelled',
  noLessonsMatch: 'No lessons match the current filters.',
  noSchoolLessons: 'No school lessons in this range.',
  filterBy: (name: string, count: number) => `Filter by ${name}: ${count} lesson${count === 1 ? '' : 's'}`,
  filterCancelled: (count: number) => `Filter cancelled classes: ${count} class${count === 1 ? '' : 'es'}`,
  lesson: (n: number) => `lesson${n === 1 ? '' : 's'}`,
  class: (n: number) => `class${n === 1 ? '' : 'es'}`,

  // Calendar view
  calendarLabel: 'Lesson calendar',
  loadingCalendar: 'Loading calendar...',
  today: 'Today',
  month: 'Month',
  week: 'Week',
  day: 'Day',
  openInMaps: (school: string) => `Open ${school} in Google Maps`,

  // Undo banner
  undoLastChange: 'Last change:',
  undoTotal: (n: number) => ` (${n} total)`,
  undo: 'Undo',
  undoing: 'Undoing...',
  dismissAllLabel: 'Dismiss all undo history',
  dismissAll: 'Dismiss all',

  // Day panel
  dailySchedule: 'DAILY SCHEDULE',
  scheduleFor: (date: string) => `Schedule for ${date}`,
  closeDayPanel: 'Close day panel',
  addLesson: 'Add lesson',
  copyAllToQuickAdd: 'Copy all to Quick Add',
  copyToMultipleDates: 'Copy to multiple dates',
  noLessonsDate: 'No lessons for this date.',
  lessonAria: (start: string, end: string, school: string, className: string, teacher: string) =>
    `${start} to ${end}: ${school}, ${className}, ${teacher}`,

  // Lesson editor
  editLesson: 'EDIT LESSON',
  newLesson: 'NEW LESSON',
  addLessonTitle: 'Add lesson',
  lessonTitle: 'Lesson',
  editLessonLabel: 'Edit lesson',
  addLessonLabel: 'Add new lesson',
  closeEditor: 'Close editor',
  date: 'Date',
  school: 'School',
  classProgramme: 'Class / programme',
  start: 'Start',
  end: 'End',
  teacher: 'Teacher',
  markUnavailable: 'Mark as unavailable',
  classCancelled: 'Class cancelled',
  saveLesson: 'Save lesson',
  duplicate: 'Duplicate',
  schoolRequired: 'School is required.',
  classRequired: 'Class is required.',

  // Recurring
  recurringLessons: 'RECURRING LESSONS',
  createWeeklyLessons: 'Create weekly lessons',
  recurringSubtitle: 'One class across a date range',
  recurringLabel: 'Create recurring weekly lessons',
  closeRecurring: 'Close recurring',
  from: 'From',
  to: 'To',
  repeatOn: 'Repeat on',
  createRecurring: 'Create recurring lessons',

  // Quick add
  quickAddTitle: 'QUICK ADD',
  addMultipleLessons: 'Add multiple lessons',
  quickAddLabel: 'Quick add multiple lessons',
  closeQuickAdd: 'Close quick add',
  draftLesson: (n: number) => `${n} draft lesson${n === 1 ? '' : 's'}`,
  lessonN: (n: number) => `Lesson ${n}`,
  remove: 'Remove',
  removeLesson: (n: number) => `Remove lesson ${n}`,
  schoolPlaceholder: 'School name',
  classPlaceholder: 'e.g. 4IN, Keyboard',
  addAnother: 'Add another lesson',
  saveN: (n: number) => `Save ${n} lesson${n === 1 ? '' : 's'}`,
  saving: 'Saving...',

  // Copy dates
  selectDates: (n: number) => `Select dates for these ${n} classes`,
  addDate: 'Add date',
  copyToDateLabel: 'Copy to date',
  noDatesSelected: 'No dates selected yet.',
  createCopies: 'Create copies',

  // Messages
  lessonsLoaded: (n: number) => `${n} lessons loaded for this view.`,
  loadError: (msg: string) => `Could not load calendar: ${msg}`,
  unknownError: 'Unknown error',
  syncDisconnected: 'Live sync disconnected. Changes may not appear in real time.',
  lessonMoved: 'Lesson moved and saved.',
  lessonSaved: 'Lesson saved.',
  lessonCancelled: 'Lesson cancelled.',
  lessonDeleted: 'Lesson deleted.',
  lessonAdded: 'Lesson added.',
  lessonsUpdated: (n: number, label: string) => `${n} lessons ${label.toLowerCase()}.`,
  lessonsDeleted: (n: number) => `${n} lessons deleted.`,
  recurringAdded: (n: number) => `${n} recurring lessons added.`,
  copiesAdded: (n: number) => `${n} lesson copies added.`,
  quickAdded: (n: number) => `${n} lessons added.`,
  undoFailed: (msg: string) => `Undo failed: ${msg}`,
  undoDone: 'Last change undone.',
  noVisibleForExport: 'There are no visible lessons to export.',
  popupBlocked: 'Please allow pop-ups to open the export preview.',
  previewOpened: (title: string) => `${title} preview opened. Click \u201cPrint / Save PDF\u201d.`,
  calendarPdfTitle: 'Music Delight Calendar',
  unassignedPdfTitle: 'Unassigned Lessons Calendar',
  cancelledPdfTitle: 'Cancelled Classes Calendar',
  teacherPdfTitle: (name: string) => `${name} Calendar`,
  schedulePdfTitle: 'Music Delight Teacher Schedule PDF',
  completeDetails: 'Complete the recurring lesson details, choose at least one weekday, and check the date range.',
  noWeekdays: 'No selected weekdays fall inside this date range.',
  completeSchoolClass: 'Complete the school and class for every lesson before saving.',
  couldNotLoadTeachers: 'Could not load teachers.',
  couldNot: (action: string, msg: string) => `Could not ${action}: ${msg}`,
  deleteConfirm: 'Delete this lesson?',
  deleteBulkConfirm: (n: number) => `Delete ${n} selected lessons?`,
  cancelBulkConfirm: (n: number) => `Cancel ${n} selected lessons?`,
  retry: 'Retry',
  liveSyncDisconnected: 'Live sync disconnected',
  filterLabel: 'Calendar filters',
} as const;