'use client';

import { useEffect, useMemo, useState } from 'react';
import { FileClock, Loader2, RefreshCw } from 'lucide-react';
import { createClient } from '../../../utils/supabase/client';

type AuditRow={id:number;occurred_at:string;operation:'INSERT'|'UPDATE'|'DELETE';actor_display_name:string|null;source:string|null;changed_fields:string[];old_row:Record<string,unknown>|null;new_row:Record<string,unknown>|null};
const label=(row:AuditRow)=>{const data=row.new_row??row.old_row??{};return `${data.school??'Lesson'} · ${data.class_name??''}`};

export default function AuditLogPage(){
 const supabase=useMemo(()=>createClient(),[]);const[rows,setRows]=useState<AuditRow[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const load=async()=>{setLoading(true);const{data,error}=await supabase.from('audit_log').select('id,occurred_at,operation,actor_display_name,source,changed_fields,old_row,new_row').order('occurred_at',{ascending:false}).limit(200);setRows((data as AuditRow[])??[]);setMessage(error?error.message:`Showing ${data?.length??0} recent lesson changes.`);setLoading(false)};useEffect(()=>{void load()},[]);
 return <main className="auditShell"><header><div><p>OPERATIONS</p><h1>Audit Log</h1><span>Who changed lessons, what changed, and when.</span></div><button onClick={()=>void load()} disabled={loading}><RefreshCw size={16}/> Refresh</button></header><div className="message">{loading?<Loader2 className="spin" size={17}/>:<FileClock size={17}/>} {message||'Loading audit log...'}</div><section>{rows.map(row=><article key={row.id}><em className={row.operation.toLowerCase()}>{row.operation}</em><div><strong>{label(row)}</strong><span>{row.changed_fields.filter(field=>field!=='updated_at').join(', ')||'New lesson record'}</span></div><div className="actor"><strong>{row.actor_display_name||'System'}</strong><span>{row.source||'unknown source'}</span></div><time>{new Intl.DateTimeFormat('en-SG',{dateStyle:'medium',timeStyle:'short'}).format(new Date(row.occurred_at))}</time></article>)}{!loading&&!rows.length&&<div className="empty">No lesson changes have been recorded yet.</div>}</section><style jsx>{`.auditShell{min-height:100vh;max-width:1250px;margin:auto;padding:34px;color:#eef2ff}header{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:18px}header p{margin:0 0 5px;color:#8b7cff;font-size:10px;font-weight:900;letter-spacing:.15em}h1{margin:0 0 5px;font-size:34px}header span,.message,article span,time{color:#8491a8}header button{display:flex;align-items:center;gap:7px;border:1px solid rgba(148,163,184,.14);border-radius:10px;background:#111a2d;color:#dce4f2;padding:10px 13px}.message{display:flex;align-items:center;gap:8px;padding:12px 14px;margin-bottom:14px;border-radius:12px;background:#0d1425}section{display:grid;gap:8px}article{display:grid;grid-template-columns:80px minmax(260px,1fr) 180px 180px;gap:14px;align-items:center;padding:15px;border:1px solid rgba(148,163,184,.12);border-radius:14px;background:#0d1425}article>div{display:grid;gap:4px}em{width:max-content;padding:6px 8px;border-radius:999px;font-size:10px;font-style:normal;font-weight:900}.insert{background:rgba(52,211,153,.12);color:#86efac}.update{background:rgba(251,191,36,.12);color:#fcd34d}.delete{background:rgba(251,113,133,.12);color:#fda4af}.actor{text-align:left}.empty{padding:35px;text-align:center;color:#8491a8}.spin{animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}@media(max-width:760px){.auditShell{padding:20px}article{grid-template-columns:auto 1fr}.actor,time{grid-column:2}}`}</style></main>;
}
